cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

before_install:
  - git clone https://github.com/NSLS-II/nsls2-ci --branch master --single-branch ~/ci_scripts
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --add channels nsls2forge
  - conda config --add channels conda-forge

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n test --file requirements/build.txt --file requirements/run.txt --file requirements/docs.txt --file requirements/test.txt
  - source activate test
  - python -m pip install . --no-deps -vv
  - git clean -xfd

script:
  - set -e
  - source activate test
  - conda install --file requirements/test.txt
  - coverage run -m pytest xpdsim/tests
  - coverage report -m
  - bash <(curl -s https://codecov.io/bash)
  - flake8 .
  - make -C docs html
  - touch docs/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: docs/_build/html
